"""Second Structure

Revision ID: 62fcf142edd9
Revises: bdc3a3295a4d
Create Date: 2025-05-06 12:39:46.922632
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62fcf142edd9'
down_revision: Union[str, None] = 'bdc3a3295a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'Alunos', 'id_responsavel', existing_type=sa.INTEGER(), nullable=True
    )
    op.create_unique_constraint(None, 'Alunos', ['rg'])
    op.create_unique_constraint(None, 'Alunos', ['cpf'])
    op.create_index(
        op.f('ix_Disciplinas_nivel'), 'Disciplinas', ['nivel'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Disciplinas_nivel'), table_name='Disciplinas')
    op.drop_constraint(None, 'Alunos', type_='unique')
    op.drop_constraint(None, 'Alunos', type_='unique')
    op.alter_column(
        'Alunos', 'id_responsavel', existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
