"""First Structure

Revision ID: bdc3a3295a4d
Revises:
Create Date: 2025-05-04 20:01:13.046007
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc3a3295a4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Disciplinas',
        sa.Column('id_disciplina', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(), nullable=False),
        sa.Column('descricao', sa.String(), nullable=False),
        sa.Column('carga_horaria', sa.Integer(), nullable=False),
        sa.Column('nivel', sa.String(), nullable=False),
        sa.Column('area_conhecimento', sa.String(), nullable=False),
        sa.Column('obrigatoria', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id_disciplina'),
    )
    op.create_index(
        op.f('ix_Disciplinas_nome'), 'Disciplinas', ['nome'], unique=False
    )
    op.create_table(
        'Professores',
        sa.Column('id_professor', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(), nullable=False),
        sa.Column('sobrenome', sa.String(), nullable=False),
        sa.Column('data_nascimento', sa.Date(), nullable=False),
        sa.Column('sexo', sa.String(), nullable=False),
        sa.Column('cpf', sa.String(), nullable=False),
        sa.Column('rg', sa.String(), nullable=False),
        sa.Column('endereco', sa.String(), nullable=False),
        sa.Column('telefone', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column(
            'data_admissao',
            sa.Date(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('formacao_academica', sa.String(), nullable=False),
        sa.Column('area_especializacao', sa.String(), nullable=False),
        sa.Column('carga_horaria_semanal', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('foto', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id_professor'),
    )
    op.create_index(
        op.f('ix_Professores_email'), 'Professores', ['email'], unique=False
    )
    op.create_index(
        op.f('ix_Professores_nome'), 'Professores', ['nome'], unique=False
    )
    op.create_index(
        op.f('ix_Professores_sobrenome'),
        'Professores',
        ['sobrenome'],
        unique=False,
    )
    op.create_index(
        op.f('ix_Professores_telefone'),
        'Professores',
        ['telefone'],
        unique=False,
    )
    op.create_table(
        'Responsaveis',
        sa.Column('id_responsavel', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(), nullable=False),
        sa.Column('sobrenome', sa.String(), nullable=False),
        sa.Column('parentesco', sa.String(), nullable=True),
        sa.Column('cpf', sa.String(), nullable=False),
        sa.Column('rg', sa.String(), nullable=False),
        sa.Column('endereco', sa.String(), nullable=False),
        sa.Column('cep', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('telefone', sa.String(), nullable=False),
        sa.Column('autorizado_buscar', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id_responsavel'),
    )
    op.create_index(
        op.f('ix_Responsaveis_email'), 'Responsaveis', ['email'], unique=False
    )
    op.create_index(
        op.f('ix_Responsaveis_nome'), 'Responsaveis', ['nome'], unique=False
    )
    op.create_index(
        op.f('ix_Responsaveis_sobrenome'),
        'Responsaveis',
        ['sobrenome'],
        unique=False,
    )
    op.create_table(
        'Turmas',
        sa.Column('id_turma', sa.Integer(), nullable=False),
        sa.Column('ano_letivo', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(), nullable=False),
        sa.Column('serie', sa.String(), nullable=False),
        sa.Column('nivel', sa.String(), nullable=False),
        sa.Column('turno', sa.String(), nullable=False),
        sa.Column('capacidade_maxima', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id_turma'),
    )
    op.create_index(op.f('ix_Turmas_nome'), 'Turmas', ['nome'], unique=False)
    op.create_table(
        'Alocacoes',
        sa.Column('id_alocacao', sa.Integer(), nullable=False),
        sa.Column('id_professor', sa.Integer(), nullable=False),
        sa.Column('id_disciplina', sa.Integer(), nullable=False),
        sa.Column('id_turma', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['id_disciplina'],
            ['Disciplinas.id_disciplina'],
        ),
        sa.ForeignKeyConstraint(
            ['id_professor'],
            ['Professores.id_professor'],
        ),
        sa.ForeignKeyConstraint(
            ['id_turma'],
            ['Turmas.id_turma'],
        ),
        sa.PrimaryKeyConstraint('id_alocacao'),
    )
    op.create_table(
        'Alunos',
        sa.Column('id_aluno', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(), nullable=False),
        sa.Column('sobrenome', sa.String(), nullable=False),
        sa.Column('data_nascimento', sa.Date(), nullable=False),
        sa.Column('sexo', sa.String(), nullable=False),
        sa.Column('cpf', sa.String(), nullable=False),
        sa.Column('rg', sa.String(), nullable=False),
        sa.Column('endereco', sa.String(), nullable=False),
        sa.Column('cep', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('telefone', sa.String(), nullable=False),
        sa.Column('foto', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('necessidades', sa.String(), nullable=True),
        sa.Column('grupo_sanguineo', sa.String(), nullable=True),
        sa.Column('medicamentos', sa.String(), nullable=True),
        sa.Column('id_responsavel', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['id_responsavel'],
            ['Responsaveis.id_responsavel'],
        ),
        sa.PrimaryKeyConstraint('id_aluno'),
    )
    op.create_index(op.f('ix_Alunos_email'), 'Alunos', ['email'], unique=False)
    op.create_index(op.f('ix_Alunos_nome'), 'Alunos', ['nome'], unique=False)
    op.create_index(
        op.f('ix_Alunos_sobrenome'), 'Alunos', ['sobrenome'], unique=False
    )
    op.create_index(
        op.f('ix_Alunos_telefone'), 'Alunos', ['telefone'], unique=False
    )
    op.create_table(
        'Frequencias',
        sa.Column('id_frequencia', sa.Integer(), nullable=False),
        sa.Column('id_aluno', sa.Integer(), nullable=False),
        sa.Column('id_disciplina', sa.Integer(), nullable=False),
        sa.Column('data', sa.Date(), nullable=False),
        sa.Column('presente', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['id_aluno'],
            ['Alunos.id_aluno'],
        ),
        sa.ForeignKeyConstraint(
            ['id_disciplina'],
            ['Disciplinas.id_disciplina'],
        ),
        sa.PrimaryKeyConstraint('id_frequencia'),
    )
    op.create_table(
        'Notas',
        sa.Column('id_nota', sa.Integer(), nullable=False),
        sa.Column('id_aluno', sa.Integer(), nullable=False),
        sa.Column('id_disciplina', sa.Integer(), nullable=False),
        sa.Column('bimestre', sa.Integer(), nullable=False),
        sa.Column('valor', sa.Float(), nullable=False),
        sa.Column(
            'data_lancamento',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['id_aluno'],
            ['Alunos.id_aluno'],
        ),
        sa.ForeignKeyConstraint(
            ['id_disciplina'],
            ['Disciplinas.id_disciplina'],
        ),
        sa.PrimaryKeyConstraint('id_nota'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Notas')
    op.drop_table('Frequencias')
    op.drop_index(op.f('ix_Alunos_telefone'), table_name='Alunos')
    op.drop_index(op.f('ix_Alunos_sobrenome'), table_name='Alunos')
    op.drop_index(op.f('ix_Alunos_nome'), table_name='Alunos')
    op.drop_index(op.f('ix_Alunos_email'), table_name='Alunos')
    op.drop_table('Alunos')
    op.drop_table('Alocacoes')
    op.drop_index(op.f('ix_Turmas_nome'), table_name='Turmas')
    op.drop_table('Turmas')
    op.drop_index(op.f('ix_Responsaveis_sobrenome'), table_name='Responsaveis')
    op.drop_index(op.f('ix_Responsaveis_nome'), table_name='Responsaveis')
    op.drop_index(op.f('ix_Responsaveis_email'), table_name='Responsaveis')
    op.drop_table('Responsaveis')
    op.drop_index(op.f('ix_Professores_telefone'), table_name='Professores')
    op.drop_index(op.f('ix_Professores_sobrenome'), table_name='Professores')
    op.drop_index(op.f('ix_Professores_nome'), table_name='Professores')
    op.drop_index(op.f('ix_Professores_email'), table_name='Professores')
    op.drop_table('Professores')
    op.drop_index(op.f('ix_Disciplinas_nome'), table_name='Disciplinas')
    op.drop_table('Disciplinas')
    # ### end Alembic commands ###
